import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { FORBIDDEN_PUBLIC_COLUMNS, PUBLIC_SERVICE_EMBEDS, PUBLIC_SERVICE_SELECT_COLUMNS, normalizeTrackingCode } from "@/lib/public/lookup";

const sql = readFileSync(
  join(process.cwd(), "supabase", "migrations", "20260925170000_public_tracking.sql"),
  "utf8",
);

function normalize(source: string) {
  return source.replace(/\s+/g, " ").toLowerCase();
}

const flat = normalize(sql);

describe("public tracking migration", () => {
  it("adds a tracking code generated by the database", () => {
    expect(flat).toContain("alter table public.cervise_services add column if not exists tracking_code text");
    expect(flat).toContain("alter column tracking_code set default upper(encode(gen_random_bytes(5), 'hex'))");
    expect(flat).toContain("alter column tracking_code set not null");
  });

  it("backfills legacy rows before the not null constraint", () => {
    const backfillIndex = flat.indexOf("where tracking_code is null loop");
    const notNullIndex = flat.indexOf("alter column tracking_code set not null");
    const defaultIndex = flat.indexOf("set default upper(encode(gen_random_bytes(5), 'hex'))");

    expect(backfillIndex).toBeGreaterThan(-1);
    expect(backfillIndex).toBeLessThan(notNullIndex);
    expect(defaultIndex).toBeGreaterThan(-1);
  });

  it("makes the code unguessable and unique", () => {
    // 5 byte = 40 bit, sehingga tebakan online tidak mungkin.
    expect(flat).toContain("gen_random_bytes(5)");
    expect(flat).toContain("create unique index if not exists cervise_services_tracking_code_idx");
    expect(flat).toContain("on public.cervise_services (tracking_code)");
  });

  it("keeps the rate limit table away from anon and authenticated", () => {
    expect(flat).toContain("create table if not exists public.public_rate_limits");
    expect(flat).toContain("alter table public.public_rate_limits enable row level security");
    expect(flat).toContain("revoke all on public.public_rate_limits from anon");
    expect(flat).toContain("revoke all on public.public_rate_limits from authenticated");
    expect(flat).toContain("grant select, insert, update, delete on public.public_rate_limits to service_role");
  });

  it("never grants a rate limit policy, so the table stays service-role only", () => {
    expect(flat).not.toContain("create policy");
  });

  it("never widens access to the service table itself", () => {
    // Grant/revoke di migration ini hanya boleh untuk public_rate_limits;
    // privileges cervise_services yang diatur di migration hardening lain.
    const privilegeLines = sql
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => /^(grant|revoke)\b/i.test(line));

    expect(privilegeLines.length).toBeGreaterThan(0);
    for (const line of privilegeLines) {
      expect(line).toContain("public_rate_limits");
      expect(line).not.toContain("cervise_services");
    }
    expect(flat).not.toContain("create policy");
    expect(flat).not.toContain("drop policy");
  });
});

describe("public tracking code contract", () => {
  it("only accepts the format the database generates", () => {
    // Default kolom adalah 10 hex huruf besar; form dan cetakan harus cocok.
    expect(normalizeTrackingCode("a3bd9f2c4b")).toBe("A3BD9F2C4B");
    expect(normalizeTrackingCode("A3BD 9F2C4B")).toBe("A3BD9F2C4B");
    expect(normalizeTrackingCode("A3BD-9F2C-4B")).toBe("A3BD9F2C4B");
    expect(normalizeTrackingCode("A3BD9F2C4")).toBeNull();
    expect(normalizeTrackingCode("G3BD9F2C4B")).toBeNull();
  });

  it("selects only columns the migrations can actually provide", () => {
    // Kalau nama kolom di select tidak ada di migration mana pun, lookup akan
    // gagal saat runtime dengan error 42703 yang tidak terlihat dari kode.
    // Kolom basis berasal dari 130000, service_number/garansi dari 150000,
    // tracking_code dari 170000.
    const combined = ["20260925130000_cervise_operational_schema", "20260925150000_service_spareparts_status", "20260925170000_public_tracking"]
      .map((file) => normalize(readFileSync(join(process.cwd(), "supabase", "migrations", `${file}.sql`), "utf8")))
      .join(" ");

    for (const column of PUBLIC_SERVICE_SELECT_COLUMNS) {
      expect(combined).toContain(column);
    }
  });

  it("reads no sensitive column", () => {
    // Embed hanya boleh membocorkan id, name, dan full_name.
    for (const embed of PUBLIC_SERVICE_EMBEDS) {
      const inside = embed.slice(embed.indexOf("(") + 1, embed.lastIndexOf(")"));
      for (const column of inside.split(",").map((part) => part.trim())) {
        expect(FORBIDDEN_PUBLIC_COLUMNS).not.toContain(column);
      }
    }

    for (const column of PUBLIC_SERVICE_SELECT_COLUMNS) {
      expect(FORBIDDEN_PUBLIC_COLUMNS).not.toContain(column);
    }
  });
});
