import { IdCardIcon, MailCheckIcon, ShieldCheckIcon, UserRoundCheckIcon } from "lucide-react";
import { getOwnerAccounts } from "../actions";
import { OwnerAccountsTable } from "@/components/owner/owner-accounts-table";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default async function OwnerAccountsPage() {
  const accounts = await getOwnerAccounts();
  const active = accounts.filter((account) => account.isActive).length;
  const unassigned = accounts.filter((account) => account.isUnassigned).length;
  const platformAdmins = accounts.filter((account) => account.isPlatformAdmin).length;
  const tenantStaff = accounts.filter((account) => account.isAssigned).length;

  return <div className="mx-auto max-w-7xl space-y-6"><div><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.3em] text-muted-foreground"><IdCardIcon className="size-3.5" /> Account registry</div><h1 className="mt-1 font-heading text-3xl">Registered accounts</h1><p className="mt-1 text-sm text-muted-foreground">Semua akun yang terdaftar di Cervise, termasuk tenant staff, platform admin, dan akun yang belum terhubung ke tenant.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-sm"><UserRoundCheckIcon className="size-4" /> Total akun</CardTitle></CardHeader><CardContent><div className="font-heading text-3xl tabular-nums">{accounts.length}</div><div className="text-xs text-muted-foreground">Registered di Supabase Auth</div></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-sm"><MailCheckIcon className="size-4" /> Aktif</CardTitle></CardHeader><CardContent><div className="font-heading text-3xl tabular-nums">{active}</div><div className="text-xs text-muted-foreground">Siap accessing Cervise</div></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-sm"><IdCardIcon className="size-4" /> Tenant staff</CardTitle></CardHeader><CardContent><div className="font-heading text-3xl tabular-nums">{tenantStaff}</div><div className="text-xs text-muted-foreground">Sudah terhubung ke tenant</div></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-sm"><ShieldCheckIcon className="size-4" /> Admin / belum terhubung</CardTitle></CardHeader><CardContent><div className="font-heading text-3xl tabular-nums">{platformAdmins + unassigned}</div><div className="text-xs text-muted-foreground">{platformAdmins} platform admin · {unassigned} unassigned</div></CardContent></Card></div><Card><CardHeader><CardTitle className="text-base">Semua akun Cervise</CardTitle><CardDescription>Data ini berasal dari akun Supabase Auth yang terdaftar, lalu diperkaya dengan profil, tenant, role, dan subscription Cervise.</CardDescription></CardHeader><CardContent><OwnerAccountsTable accounts={accounts} /></CardContent></Card></div>;
}
